
-- Validating data

SELECT * FROM customer

LIMIT 10





-- What is the total revenue generated by male vs. female customers?





SELECT 

	gender, SUM(purchase_amount) AS revenue

FROM customer

GROUP BY gender



-- Which customers used a discount but still spent more than the average purchase amount?


SELECT 
	
	customer_id 

FROM customer 

WHERE discount_applied = 'Yes' AND purchase_amount > (select AVG(purchase_amount) FROM customer)





-- Which are the top 5 products with the highest average review rating?


SELECT 
	
	item_purchased, 
	
	ROUAVG(review_rating) AS avg_review

FROM customer

GROUP BY item_purchased

ORDER BY  AVG(review_rating) DESC

LIMIT 5



-- Compare the average Purchase Amounts between Standard and Express Shipping.


SELECT 

	shipping_type,

	ROUND(AVG(purchase_amount),2) AS avg_amount

FROM customer

WHERE shipping_type in ('Standard','Express')

GROUP BY shipping_type



-- Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.


SELECT 

	subscription_status,

	COUNT(customer_id) AS no_of_customers,

	ROUND(AVG(purchase_amount),2) AS avg_amount,

	ROUND(SUM(purchase_amount),2) AS revenue

FROM customer

GROUP BY subscription_status




-- Which 5 products have the highest percentage of purchases with discounts applied 



SELECT 
	
	item_purchased,

	ROUND((100 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) / COUNT(*) ),2) AS percentage

FROM customer

GROUP BY item_purchased




-- Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment.


WITH CTE AS (

	SELECT customer_id,
	
	previous_purchases,

	CASE 
		WHEN previous_purchases = 1 THEN 'New'

		WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'

		ELSE 'Loyal'

	END AS customer_type

FROM customer

)


SELECT 

	 customer_type,

	 COUNT(*) AS no_of_customers

FROM CTE

GROUP BY customer_type




-- What are the top 3 most purchased products within each category?


WITH CTE AS (

	SELECT 
		
		category,
			
		item_purchased, 
		
		COUNT(*) AS total_orders,

		ROW_NUMBER() OVER(partition by category ORDER BY COUNT(*) DESC) AS item_rank
	
	FROM customer
	
	GROUP BY category,item_purchased
	
)


SELECT 
	
	* 

FROM CTE

WHERE item_rank <= 3


	

-- Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?


SELECT 

	subscription_status,

	COUNT(customer_id) AS no_of_customers

FROM customer

WHERE previous_purchases > 5

GROUP BY subscription_status



-- What is the revenue contribution of each age group?

SELECT 
	
	age_group, 
	
	 SUM(purchase_amount) AS revenue

FROM customer

GROUP BY age_group


ORDER BY revenue DESC



